### PR TITLE
Cleanup code

### PR DESCRIPTION
**Pull request by mihaimaruseac**
While working on the high scores implementation I decided to add extra warnings flags to the cabal file to make the code future proof (in case of a change in the libraries or the code you'll get a notification at compile time instead of a runtime `undefined` error).

I also updated the code to follow some Haskell style guidelines.

Will send you a new PR today and then later this week the high-scores one.

### CODE REVIEW

**Comment by hauxir** [comment]
Seems great, I'll look at this ASAP :)

**Comment by mihaimaruseac** [comment]
Sure, I have opened 4 PRs in totals and I'm working on more.

**Comment by chrisvilain** [comment]
Pretty good at first glance. Great to see this student project still moving on :) thanks for the pr !

**Comment by hauxir** [comment]
I've merged your other PR's. You will need to resolve some conflicts here. Great job!

**Comment by mihaimaruseac** [comment]
Thanks. Conflicts resolved. I'll look over the weekend on the top scores.

**Pull request merged**
